name: Go package

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
